<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MVC</title>
    <link href="<?= DIR; ?>public/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?= DIR; ?>public/css/font-awesome.min.css" rel="stylesheet">
    <link href="<?= DIR; ?>public/css/default.css" rel="stylesheet">
    <link href="<?= DIR; ?>public/css/famfamfam-flags.css" rel="stylesheet">
    <script type="text/javascript">var DIR="<?=DIR;?>";</script>
</head>
<body>
